<?php

namespace Tests\Feature;

use App\Models\TodoList;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class TodoListTest extends TestCase
{
    use RefreshDatabase;

    private $list;

    public function setup(): void
    {
        parent::setup(); // TODO: Change the autogenerated stub
        $this->list =  TodoList::factory()->create();
    }

    public function test_fetch_all_todo_lists()
    {
        $response = $this->getJson(route('todo-list.index'))
            ->assertOk()
            ->assertJsonStructure([
                'data'=>[
                    '*'=>['id','name','created_at','updated_at']
                ],
            ])->json();
        $this->assertCount(1, $response['data']);

    }

    public function test_fetch_single_todo_list()
    {
        $response = $this->getJson(route('todo-list.show',$this->list->id))
                        ->assertOk()
                        ->json();
        $this->assertEquals($response['data']['name'], $this->list->name);

    }

    public function test_store_new_todo_list()
    {
        $list = TodoList::factory()->make();
        $response = $this->postJson(route('todo-list.store'),['name'=>$list->name])
            ->assertCreated()
            ->json();
        $this->assertDatabaseHas('todo_lists',['name'=>$list->name]);
        $this->assertEquals($response['data']['name'], $list->name);

    }
}

